/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-SMJ.h
 #	source generated by 4D Plugin Wizard
 #	Project : SMJ
 #	author : miyako
 #	2021/07/31
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_SMJ_H
#define PLUGIN_SMJ_H

#include "4DPluginAPI.h"
#include "4DPlugin-JSON.h"
#if VERSIONWIN
#include "setupapi.h"
#include "Ntddser.h"
#endif
#pragma mark -

static void SMJ_Request(PA_PluginParameters params);

#endif /* PLUGIN_SMJ_H */
